name: Deploy to OVH

on:
  push:
    branches: [main] # déclenche à chaque push sur main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check-out repo
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 22 # la version que tu utilises

      - name: Install PNPM
        uses: pnpm/action-setup@v3
        with:
          version: 8

      - run: pnpm install # ou npm ci
      - run: pnpm run build # produit dist/

      - name: Upload via FTP
        uses: SamKirkland/FTP-Deploy-Action@v5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: dist # ce qu’on envoie
          server-dir: /www # dossier racine OVH
          protocol: ftp # explicite : pas de TLS
