# .github/workflows/deploy.yml
name: Deploy to OVH (npm)

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4 # installe Node
        with:
          node-version: "20" # adapte si besoin
          cache: "npm" # mise en cache du dossier ~/.npm

      - run: npm ci # installe depuis package-lock.json
      - run: npm run build # crée le dossier dist/

      - name: Upload via FTPS
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          protocol: ftps
          port: 21
          local-dir: ./dist/ # <— bien finir par /
          server-dir: ./ # ou ./www/ selon ton multisite
          log-level: standard
          dangerous-clean-slate: true # vide le dossier avant upload (optionnel)
