# .github/workflows/deploy.yml
name: Deploy to OVH (FTP)

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - run: npm ci # reproduit package-lock.json :contentReference[oaicite:3]{index=3}
      - run: npm run build # ➜ dist/

      - name: Upload via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5 # ne gère que ftp / ftps :contentReference[oaicite:4]{index=4}
        with:
          server: ftp.cluster021.hosting.ovh.net
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          protocol: ftp # 🔑
          port: 21
          local-dir: ./dist/ # slash final obligatoire
          server-dir: ./www/ # dossier racine défini dans Multisite
          dangerous-clean-slate: true
